title: "Phani Varma Pericharla"
description: "My personal portfolio website"
url: "https://yourusername.github.io"
theme: jekyll-theme-cayman # Or choose from supported themes
author: Your Name

# Social Links
linkedin_username: your-linkedin-username
github_username: yourusername
email: your.email@example.com

# Google Analytics (optional)
google_analytics: UA-XXXXXXXXX-X

# Build settings
markdown: kramdown
